[package]
name = "tango"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.18"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
crossbeam-channel = "0.5"

[[bench]]
name = "channel_comparison"
harness = false
